#index:
#    path: /
#    controller: App\Controller\DefaultController::index

test:
    path: /pvreception
    controller: App\Controller\name::reception
    methods: [POST, GET]

detail_pv:
    path: /proces/affiche/{valeur}
    controller: App\Controller\LogistiqueController:detail_PV
    methods: [POST, GET]